// export const DATA_SET_FETCH = 'data_set_fetch';
// export const POST_TITLE = 'post_title';
// export const POST_CONTENT = 'post_content';
// export const USERNAME_CHANGE = 'username_change';
// export const BIO_CHANGE = 'bio_change';
// export const WORKPLACE_CHANGE = 'workplace_change';
// export const DESIGNATION_CHANGE = 'designation_change';
export const USERNAME_SET='username_set'
export const USERID_SET='userid_set'