export const USERNAME_SET='username_set'
export const USERID_SET='userid_set'
export const CHATUSERNAME_SET='chatusername_set'
export const REPLY_LIST='reply_list'
export const MODAL_VISIBLE= 'modal_visible'
export const AVATAR_SET='avatar_set'