export const USERNAME_SET='username_set'
export const USERID_SET='userid_set'
export const CHATUSERNAME_SET='chatusername_set'
export const REPLY_LIST='reply_list'
export const MODAL_VISIBLE= 'modal_visible'
export const AVATAR_SET='avatar_set'
export const COMMENT_ADDED='comment_added'
export const FRIEND_LIST='friend_list'
export const FILTER_FRIEND_LIST='search_friend_list'
export const SEARCH_BOX_VALUE='search_box_value'
export const COUNT='count'

